### ISSUE TITLE
Export utilities to ease lib customization

### ISSUE THREAD

**Issue by pineapplethief** [yury-dymov/redux-oauth#10]
Hi!
I have a lot of trouble customizing this lib to email/password authentication cause various utilities like `getHeaders`, `parseHeaders`, `getSettings`, `prepareHeadersForFetch` are not exported from the module. It would be great if module exported most/all of its files, since you already pointed out in readme it's not covering all use-cases.
P.S. it also would be great if working example of email/password authentication could be included in docs, i've already spent couple of days trying to get it work and no luck so far

**Comment by yury-dymov** [comment]
@pineapplethief, I don't have much time for that now :/ 

What is wrong with 
```
function signIn(email, password) {
    return dispatch => {
        dispatch(authenticateStart());

        return dispatch(fetch(yourCustomAuthMethod(email, password)))
            .then(parseResponse)
            .then(user => {
                dispatch(authenticateComplete(user));

                // it is recommended to return resolve or reject for server side rendering case.
                // It helps to know then all requests are finished and rendering can be performed
                return Promise.resolve(user);
            }
            .catch(error => {
                if (error.errors) {
                    dispatch(authenticateError(error.errors));
                }

                return Promise.reject(error.errors || error);
            };
    };
}
```

Generally speaking, you don't need to access all the internals.

**Comment by pineapplethief** [comment]
I finally figured it out, turns out it was CORS/headers issue, had to write my own wrapper around `fetch` provided by your lib + plus whitelist all auth headers in rails backend explicitly. I could add documentation PR to clarify CORS issues + how to add custom headers some time later, if it's ok with you, I guess I'm not the only one mouting api to `api.domain.com` subdomain:)

**Comment by yury-dymov** [comment]
:)

Well, backend configuration is a different story but it might be beneficial for others to avoid such issues in the future, so I would merge such PR with pleasure.

I configured CORS long time, so forgot already all the pitfalls I experienced myself :)
