### ISSUE TITLE
How can I catch errors from server response?

### ISSUE THREAD

**Issue by far4599** [yury-dymov/redux-oauth#3]
I want to use PHP as backend and do not understand how to return errors from server to client via pop up. Could you help?

**Comment by yury-dymov** [comment]
Hi @far4599,

can you explain your use case in more details? 

For example, you can render your error using PHP, so it would be represented as a page to the user in the popup. Or you want to send error message to the frontend and render it there?

**Comment by far4599** [comment]
I restrict users to login only with one social network. So if they use another network account with the same email, error shall be shown. 

I need errors in the frontend so I can show it in some kind of modal or alert. Not in the pop up used for authentication.

Is it possible without modifying your package?



Отправлено из мобильной Почты Mail.Ru


понедельник, 27 февраля 2017 г., 8:44 +0300 от Yury Dymov  <notifications@github.com>:

**Comment by yury-dymov** [comment]
Got you. 

Modification is required in this case. Currently you either return payload and popup is closed or render error in the popup. When user closes the popup manually after reviewing the error, front end app returns back to the state before user clicked on sign in button.

**Comment by far4599** [comment]
Ok, thx



Отправлено из мобильной Почты Mail.Ru


понедельник, 27 февраля 2017 г., 19:03 +0300 от Yury Dymov  <notifications@github.com>:
