### ISSUE TITLE
Is it possible to use my own state?

### ISSUE THREAD

**Issue by LeoNero** [yury-dymov/redux-oauth#4]
My store looks like the following:

```
user: {
   token: ''
}
```

Is it possible to store the token in my custom state?

**Comment by yury-dymov** [comment]
Yes, just to listen to the relevant events: https://github.com/yury-dymov/redux-oauth/blob/master/src/reducers/headers.js

```
import { UPDATE_HEADERS } from 'redux-oauth';

...
```

**Comment by LeoNero** [comment]
Thanks!

**Comment by LeoNero** [comment]
@yury-dymov If I dont use `authStateReducer`, I get the following error: `Uncaught TypeError: Cannot read property 'getIn' of undefined`

**Comment by yury-dymov** [comment]
Well, that makes sense. If you don't need, what library does, just don't use it :) Solution above suggests you, how to store token not only in redux-oauth library reducer but somewhere else as well.
