### ISSUE TITLE
What is apiUrl exactly doing?

### ISSUE THREAD

**Issue by Shadowman4205** [yury-dymov/redux-oauth#5]
Navigating to heroku api, what exactly happening inside there? I am new to this oauth autentication and implementing it to react-redux.

**Comment by yury-dymov** [comment]
`apiUrl` is pointing to the backend endpoint, which is responsible for validating auth token and providing app data.

But I didn't get your question to be honest as title and description are a bit misleading. If you are looking for the basic info, how things work in general, then this is not a right place to start with...

**Comment by Shadowman4205** [comment]
Any good source so i can understand it?
I want know what exactly happen when u navigate to heroku api in ur example. Are you just navigate there and happen the Request? HTTP GET http://github.com/login/oauth/authorize or you pass extra info with GET like http://github.com/login/oauth/authorize?****
Sorry for inconvenience, and thank you.

**Comment by Shadowman4205** [comment]
Are you doing this on ur heroku api?

```
var oauth = require("oauth").OAuth2;
var OAuth2 = new oauth(GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, "https://github.com/", "login/oauth/authorize", "login/oauth/access_token");

app.get('/auth/github',function(req,res){
   res.writeHead(303, {
     Location: OAuth2.getAuthorizeUrl({
       redirect_uri: 'http://127.0.0.1:3000/auth/github/callback',
       scope: "user,repo,gist"
     })
    });
    res.end();
});

app.get('/auth/github/callback',function (req, res) {
  var code = req.query.code;
  OAuth2.getOAuthAccessToken(code, {}, function (err, access_token, refresh_token) {
    if (err) {
      console.log(err);
    }
    accessToken = access_token;
    // authenticate github API
    console.log("AccessToken: "+accessToken+"\n");
    github.authenticate({
      type: "oauth",
      token: accessToken
    });
  });
  res.redirect('home');
});
```

**Comment by yury-dymov** [comment]
1. JS app is opening a popup with backend URL, which is responsible for oauth. It contains several URL query parameters like callback URL
2. Backend app creates a session and forwards request to the oauth provider (i.e. facebook). 
3. If everything is OK, facebook redirects us back to the backend with some additional parameters
4. Backend uses these parameters, establishing connection to the oauth provider, validates the keys, and fetches user data (email, name, whatever)
5. Backend issues its own auth token with encrypted information of the user (user id, email, whatever) and sends it back via the callback url provided in step 1 with a payload encoded in URL query.
6. Now both browser tabs (initiator and popup) are sharing the same domain, so initiator can read the payload from the URL, close the tab and save token in the cookies or local storage.
