### ISSUE TITLE
dependency to immutable js (and lodash)

### ISSUE THREAD

**Issue by rolele** [yury-dymov/redux-oauth#6]
Hi, thanks for this package.
It is good to have a lightweight solution for authentication with redux.
Now I found that the dependency to immutable js is quite big as you an see on the picture:
<img width="1351" alt="screen shot 2017-06-18 at 11 06 07 pm" src="https://user-images.githubusercontent.com/22406571/27260909-ff5eadc8-547a-11e7-8383-cf943d05937e.png">

Do you think it is possible to remove that dependency at all ?

**Comment by rolele** [comment]
Actually I also think the redix-oauth library included the lodash library as well in my client bundle. 
Do you think this is also necessary as well ?

**Comment by yury-dymov** [comment]
Hey @rolele 

1) I am fine to drop immutable.js but I don't have time now to do so. If you want to submit a PR, I will merge it
2) redux-oauth doesn't include itself anything. Webpack (or whatever you are using for bundling) during build time include parts of lodash, which are used across all packages, and only once. I am using only very small portion of lodash (5 functions or so), each included function is imported explicitly (i.e. `import assign from 'lodash/assign'`), so in the final bundle only very small portion of lodash (several kilobytes) will be included.

**Comment by yury-dymov** [comment]
Closing this. PRs are still welcome though
